version: '3'
services:
  bbb-meetings-json:
    container_name: "bbb-meetings-json"
    image: mohammad362/bbb-meetings-json:1.0
    ports:
      - "8000:8000"
    volumes:
      - ./config.env:/app/config.env
    restart: unless-stopped
